{{- if and (not .Values.customScheduler.external) .Values.k8s.persistence.enabled .Values.customScheduler.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-custom-scheduler-pvc
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
{{- if not .Values.k8s.persistence.hasDefaultStorageClass }}
  storageClassName: {{ .Values.k8s.persistence.explicitStorageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.customScheduler.persistence.size }}
{{- end }}
